package(default_visibility = ["//visibility:public"])
cc_binary(
    name = "rejection_probe",
    srcs = ["rejection_probe.cc"],
    deps = [
        "//examples/sampling_c3:generate_samples",
        "//examples/sampling_c3:sampling_c3_utils",
        "//examples/sampling_c3/parameter_headers:sampling_c3_controller_params",
        "//examples/sampling_c3/parameter_headers:franka_sim_params",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
    linkopts = ["-L/lib/x86_64-linux-gnu", "-lopenblas"],
)
